### ISSUE TITLE
1주차) Component & Props , Event & State

### ISSUE THREAD

**Issue by juhwanHeo** [juhwanHeo/study-react#8]
> branch & PR
PR Title은 `study 주차구분 / 내용 / 각자이름`으로 올려주시고, 
ex) Week 1 / Multi Container Pod / juhwan
Branch naming은 `week1/{각자이름}` 입니다.
ex) week1/juhwan

>폴더링
과제 컴포넌트들의 path는 `/{이름}/board-project/src/components/`이 기본이 되고, 나머지 폴더링은 수정 가능합니다.

### 과제 1) Board Component
path: /{이름}/board-project/src/components/Board.js

Header가 Seq, Title, Creator 3가지를 가지는 table 형식의 화면을 구성해 주세요.
| Seq | Title | Creator |
|-------|-------|-------|
| 1 | Test 제목 1  | Test 생성자 1   |
| 2 | Test 제목 2  | Test 생성자 2  |
| 3 | Test 제목 3  | Test 생성자 3   |

~아래 이미지는 Article 이 없을 때의 예시입니다.~
아래 이미지는 BoardItem 이 없을 때의 예시입니다.

![image](https://github.com/user-attachments/assets/ecdf8983-8812-44dd-b0d0-00e2b5d11624)

### 과제 2)
~Article Component~
~path: /{이름}/board-project/src/components/Article.js~
BoardItem Component
path: /{이름}/board-project/src/components/BoardItem.js

~(과제 1)의 Board Component 자식으로 Article Component를 만들어 주세요.~

(과제 1)의 Board Component List Item으로 BoardItem Component를 만들어 주세요.

- `useState`라는 Hook을 사용해도 좋습니다.

```json
[
  {
    "id": 1,
    "title": "title 1",
    "content": "content 1",
    "creator": "creator 1",
  },
  {
    "id": 2,
    "title": "title 2",
    "content": "content 2",
    "creator": "creator 2",
  },
  {
    "id": 3,
    "title": "title 3",
    "content": "content 3",
    "creator": "creator 3",
  }
]
```

### 과제 3)
~path: /{이름}/board-project/src/components/Article.js~
path: /{이름}/board-project/src/components/BoardItem.js

[fetch API](https://developer.mozilla.org/ko/docs/Web/API/Fetch_API/Using_Fetch) 
[Promise](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise)

`GET http://heojh.iptime.org:8003/board`

#### 발표자: 김보혜
- [React 2022년 개정판 - 8. Create](https://youtu.be/kctNCMFxciQ?feature=shared)
- [React 2022년 개정판 - 9. Update
](https://youtu.be/bW_WOrYzVWw?feature=shared)
- [React 2022년 개정판 - 10. Delete & 수업을 마치며](https://youtu.be/OZPRKFqPWG4?feature=shared)

#### 발표자:  이주원
- [조건부 렌더링](https://ko.legacy.reactjs.org/docs/conditional-rendering.html)
- [리스트와 Key](https://ko.legacy.reactjs.org/docs/lists-and-keys.html)

**Comment by Mik-WJ** [comment]
GET http://heojh.iptime.org:8003/board 
해당 주소에 get 해도 Response가 따로 오지 않습니다.

**Comment by juwonlee-dev** [comment]
> GET http://heojh.iptime.org:8003/board 해당 주소에 get 해도 Response가 따로 오지 않습니다.

해당 과제는 다음주차 과제입니다.
